[package]
name = "rust-quiz"
version = "0.1.0"
edition = "2018"
authors = ["Benjamin Massey"]

[dependencies]
bevy = "0.5"
bevy_prototype_lyon = "0.3.1"
rand = "0.6"
string-error = "0.1.0"
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
